### ISSUE TITLE
 could not import github.com/xx/xx/xx (can't find import:

### ISSUE THREAD

**Issue by MichaelSmith01** [ttarvis/glasgo#1]
if  file.go include "import relative lib",such as 
import github.com/xx/xx/xx
execute  glasgo   file.go
will report "could not import github.com/xx/xx/xx (can't find import:"

**Comment by ttarvis** [comment]
Hi,

Would you try to execute the tool again but use the '-source' flag? As below:

./Glasgo -source file.go

Please report if this resolves the issue.  This feature is currently not documented.

**Comment by MichaelSmith01** [comment]
resolved my first issue.

**Comment by ttarvis** [comment]
ok.  This issue is related to the way that the source is imported via the importer package.  It may be best to change the default so that a flag is not necessary.  I will have to think about it and maybe look for more feedback.  It is certainly the case though, that the documentation should include something about this flag.  Thanks.  I will close this issue now.
